apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shop
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/AdidR10/k8s-devops-pipeline.git
    targetRevision: my-lab-4
    path: charts/shop
  destination:
    server: https://kubernetes.default.svc
    namespace: shop
  syncPolicy:
    automated:
      selfHeal: true    # revert manual cluster changes (drift)
      prune: true       # delete objects removed from Git
    syncOptions:
      - CreateNamespace=true