global:
  imageRepo: adidr10   # matches DOCKERHUB_USERNAME
  imageTag: 5227d1feff849927102133b7ad03d11c5657d8c6

frontend:
  replicas: 1
productsApi:
  replicas: 1
ordersApi:
  replicas: 1
gateway:
  nodePort: 30080
imagePullSecrets: []